import type { AuditAction } from "@/lib/audit";

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  "auth.login.success": "ورود موفق",
  "auth.login.failed": "تلاش ناموفق ورود",
  "auth.login.locked": "قفل شدن حساب",
  "auth.logout": "خروج از حساب",
  "auth.register": "ثبت‌نام کاربر جدید",
  "auth.password.reset_requested": "درخواست بازیابی رمز عبور",
  "auth.password.reset_completed": "بازیابی رمز عبور انجام شد",
  "auth.password.changed": "تغییر رمز عبور",
  "auth.2fa.enabled": "فعال‌سازی احراز دو مرحله‌ای",
  "auth.2fa.disabled": "غیرفعال‌سازی احراز دو مرحله‌ای",
  "user.role.changed": "تغییر نقش کاربر",
  "user.status.changed": "تغییر وضعیت کاربر",
  "user.created": "ایجاد کاربر",
  "user.deleted": "حذف کاربر",
  "product.created": "ایجاد محصول",
  "product.updated": "ویرایش محصول",
  "product.deleted": "حذف محصول",
  "product.release.created": "انتشار نسخه جدید",
  "license.created": "صدور لایسنس",
  "license.revoked": "ابطال لایسنس",
  "license.suspended": "مسدودسازی لایسنس",
  "license.activated": "فعال‌سازی لایسنس",
  "license.deactivated": "غیرفعال‌سازی لایسنس",
  "order.created": "ثبت سفارش",
  "order.paid": "پرداخت موفق سفارش",
  "order.failed": "شکست پرداخت سفارش",
  "settings.ai_provider.updated": "به‌روزرسانی تنظیمات هوش مصنوعی",
  "settings.sms_gateway.updated": "به‌روزرسانی تنظیمات پیامک",
  "settings.payment.updated": "به‌روزرسانی تنظیمات پرداخت",
  "settings.general.updated": "به‌روزرسانی تنظیمات عمومی",
  "api_key.created": "ایجاد کلید API",
  "api_key.revoked": "ابطال کلید API",
  "kb.document.ingested": "افزودن سند به پایگاه دانش",
  "kb.document.deleted": "حذف سند از پایگاه دانش",
};
